# --- !Ups

CREATE TABLE CAT
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COLOR VARCHAR(255) NOT NULL
);

CREATE TABLE DOG
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COLOR VARCHAR(255) NOT NULL
);

# --- !Downs

drop table "CAT";
drop table "DOG";